### ISSUE TITLE
pip install multiprocessing failed due to Python 2 / 3 issue

### ISSUE THREAD

**Issue by anhqle** [hamelsmu/Docker_Tutorial#1]
While following your tutorial I ran into the following error:

```
Step 7/16 : RUN pip --no-cache-dir install --upgrade         multiprocessing         sklearn-pandas
 ---> Running in 036a8a985fb1
Collecting multiprocessing
  Downloading multiprocessing-2.6.2.1.tar.gz (108kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-uvo7qdlq/multiprocessing/setup.py", line 94
        print 'Macros:'
                      ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-uvo7qdlq/multiprocessing/
The command '/bin/sh -c pip --no-cache-dir install --upgrade         multiprocessing         sklearn-pandas' returned a non-zero code: 1
```

It seems to me that this is a Python 2 / 3 issue given the error message regarding parentheses in `print`.

**Comment by hamelsmu** [comment]
@LaDilettante which step are you running, specifically?

**Comment by hamelsmu** [comment]
This has been fixed with PR https://github.com/hamelsmu/Docker_Tutorial/pull/4

**Comment by hamelsmu** [comment]
https://github.com/hamelsmu/Docker_Tutorial/pull/4
